version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /control-plane
      - /node-agent
      - /images/guest/cmd/vsock-ssh-agent-proxy
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: chore
      include: scope
    groups:
      go-minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: cargo
    directory: /pod-daemon
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: chore
      include: scope
    groups:
      cargo-minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: ci

  - package-ecosystem: docker
    directory: /images/guest
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: chore
      include: scope
